<div class="header">
  <div style="font-size: 8px; text-align: right; padding-right: 8px;">Pi-Star:<?php echo $configPistarRelease['Pi-Star']['Version']?> / Dashboard:<?php echo $version; ?></div>
  <h1>Pi-Star Digital Voice - Expert Editor</h1>
  <p style="padding-right: 5px; text-align: right; color: #ffffff;">
    <a href="/" style="color: #ffffff;"><?php echo $lang['dashboard'];?></a> |
    <a href="/admin/" style="color: #ffffff;"><?php echo $lang['admin'];?></a> |
    <a href="/admin/update.php" style="color: #ffffff;"><?php echo $lang['update'];?></a> |
    <a href="/admin/config_backup.php" style="color: #ffffff;"><?php echo $lang['backup_restore'];?></a> |
    <a href="/admin/configure.php" style="color: #ffffff;"><?php echo $lang['configuration'];?></a>
  </p>
  <p style="padding-right: 5px; text-align: right; color: #ffffff;">
    <b>Quick Editors:</b>
    <a href="edit_dstarrepeater.php" style="color: #ffffff;">DStarRepeater</a> |
    <a href="edit_ircddbgateway.php" style="color: #ffffff;">ircDDBGateway</a> |
    <a href="edit_timeserver.php" style="color: #ffffff;">TimeServer</a> |
    <a href="edit_mmdvmhost.php" style="color: #ffffff;">MMDVMHost</a> |
    <a href="edit_dmrgateway.php" style="color: #ffffff;">DMRGateway</a> |
    <a href="edit_ysfgateway.php" style="color: #ffffff;">YSFGateway</a> |
    <a href="edit_p25gateway.php" style="color: #ffffff;">P25Gateway</a><br />
    <b>Full Editors:</b>
    <a href="fulledit_dmrgateway.php" style="color: #ffffff;">DMRGateway</a> |
    <a href="fulledit_pistar-remote.php" style="color: #ffffff;">PiStar-Remote</a> |
    <a href="fulledit_wpaconfig.php" style="color: #ffffff;">WiFi Config</a>
    <b>Tools:</b>
    <a href="ssh_access.php" style="color: #ffffff;">SSH Access</a>
  </p>
  </div>
