<div class="header">
  <div style="font-size: 8px; text-align: right; padding-right: 8px;">Pi-Star:<?php echo $configPistarRelease['Pi-Star']['Version']?> / Dashboard:<?php echo $version; ?></div>
  <h1>Pi-Star Digital Voice - Expert Editors</h1>
  <p style="padding-right: 5px; text-align: right; color: #ffffff;">
    <a href="/" style="color: #ffffff;"><?php echo $lang['dashboard'];?></a> |
    <a href="/admin/" style="color: #ffffff;"><?php echo $lang['admin'];?></a> |
    <a href="/admin/update.php" style="color: #ffffff;"><?php echo $lang['update'];?></a> |
    <a href="/admin/expert/upgrade.php" style="color: #ffffff;">Upgrade</a> |
    <a href="/admin/config_backup.php" style="color: #ffffff;"><?php echo $lang['backup_restore'];?></a> |
    <a href="/admin/configure.php" style="color: #ffffff;"><?php echo $lang['configuration'];?></a>
  </p>
  <p style="padding-right: 5px; text-align: right; color: #ffffff;">
    <b>Quick Edit:</b>
    <a href="edit_dstarrepeater.php" style="color: #ffffff;">DStarRepeater</a> |
    <a href="edit_ircddbgateway.php" style="color: #ffffff;">ircDDBGateway</a> |
    <a href="edit_timeserver.php" style="color: #ffffff;">TimeServer</a> |
    <a href="edit_mmdvmhost.php" style="color: #ffffff;">MMDVMHost</a> |
    <a href="edit_dmrgateway.php" style="color: #ffffff;">DMR GW</a> |
    <a href="edit_ysfgateway.php" style="color: #ffffff;">YSF GW</a> |
    <a href="edit_p25gateway.php" style="color: #ffffff;">P25 GW</a> |
    <a href="edit_nxdngateway.php" style="color: #ffffff;">NXDN GW</a> |
    <a href="edit_dapnetgateway.php" style="color: #ffffff;">DAPNET GW</a><br />
    <b>Full Edit:</b>
    <a href="fulledit_dmrgateway.php" style="color: #ffffff;">DMR GW</a> |
    <a href="fulledit_pistar-remote.php" style="color: #ffffff;">PiStar-Remote</a> |
    <a href="fulledit_wpaconfig.php" style="color: #ffffff;">WiFi</a> |
    <a href="fulledit_bmapikey.php" style="color: #ffffff;">BM API</a> |
    <a href="fulledit_dapnetapi.php" style="color: #ffffff;">DAPNET API</a> |
    <a href="fulledit_cron.php" style="color: #ffffff;">System Cron</a> |
    <a href="fulledit_rssidat.php" style="color: #ffffff;">RSSI Dat</a>
    &emsp;<b>Tools:</b>
    <a href="edit_dashboard.php" style="color: #ffffff;">CSS Tool</a> |
    <a href="modem_fw_upgrade.php" style="color: #ffffff;">FW</a> |
    <a href="ssh_access.php" style="color: #ffffff;">SSH Access</a>
  </p>
  </div>
