#       ircddbgateway_languages.inc
#
#       Written for Pi-Star Digital Voice Node by Andy Taylor (MW0MWZ)
#       Orrigional request by Dennis Bonesky
#
#       Updated 28-May-2017
#
#
#
# Language      ircddbgateway           timeserver
# Displayed     config                  config
#######################################################################
English_UK      0                       0
English_US      1                       1
German          2                       2
Danish          3                       0
French          4                       3
Italian         5                       0
Polish          6                       0
Spanish         7                       0
Swedish         8                       4
Dutch           9                       0
Norwegian       10                      0
Portuguese      11                      0
