# ircddbgateway_languages.inc
#
# Written for Pi-Star Digital Voice by Andy Taylor (MW0MWZ)
# Orrigional request by Dennis Bonesky
#
# Updated 28-May-2017
#
###########################################################
#language;ircddbgateway;timeserver
###########################################################
English_(UK);0;0
Deutsch;1;4
Dansk;2;0
Francais;3;6
Italiano;4;0
Polski;5;0
English_(US);6;2
Espanol;7;9
Svenska;8;8
Nederlands_(NL);9;7
Nederlands_(BE);10;7
Norsk;11;10
Portugues;12;11
###########################################################
